#! /bin/sh
#
# Startup Init Script for ispman-agent
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/share/ispman/bin/ispman-agent
NAME=ispman-agent
DESC=ispman-agent
DAEMON_OPTS=nodetach

test -x $DAEMON || exit 0

# Include ispman defaults if available
if [ -f /etc/default/$NAME ] ; then
	. /etc/default/$NAME
fi

if [ "${START}" != "true" ] ; then
	echo "ispman-agent is currently disabled. Set START=true in /etc/default/ispman-agent!"
	exit 0
fi

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -m -b --start --quiet --pidfile /run/$NAME.pid \
		--exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --oknodo --pidfile /run/$NAME.pid 
	rm -f /run/$NAME.pid
	echo "$NAME."
	;;
  #reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
	# echo "Reloading $DESC configuration files."
	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
	#	/run/$NAME.pid --exec $DAEMON
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --oknodo --pidfile /run/$NAME.pid 
	rm -f /run/$NAME.pid
	sleep 1
	start-stop-daemon -m -b --start --quiet --pidfile /run/$NAME.pid \
	--exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
